[package]
name = "badges"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
askama = "0.16.1"
axum = { version = "0.8", default-features = false, features = ["query"] }
base64 = "0.22"
csscolorparser = "0.8"
infer = { version = "0.19", default-features = false }
mime = "0.3"
palette = { version = "0.7", default-features = false, features = ["std"] }
roxmltree = "0.21"
rustybuzz = "0.20.1"
serde = { version = "1.0.229", features = ["derive"] }
svgtypes = "0.16"
thiserror = "2"
url = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-util = { version = "0.3", default-features = false }
tower-service = "0.3.3"
worker = { version = "0.8", features = ["axum", "http"] }

[dev-dependencies]
serde_urlencoded = "0.7"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
